// <auto-generated />
using System;
using DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20260624231828_AddMustChangePasswordToUser")]
    partial class AddMustChangePasswordToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DAL.Entities.AcademicTerm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("term_order");

                    b.HasKey("Id")
                        .HasName("academic_terms_pkey");

                    b.HasIndex(new[] { "Name" }, "academic_terms_name_key")
                        .IsUnique();

                    b.ToTable("academic_terms", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetTable")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("target_table");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("audit_logs_pkey");

                    b.HasIndex(new[] { "CreatedAt" }, "idx_audit_logs_created_at");

                    b.HasIndex(new[] { "UserId" }, "idx_audit_logs_user_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("RetrievedChunkIds")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("retrieved_chunk_ids")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id")
                        .HasName("chat_messages_pkey");

                    b.HasIndex(new[] { "CreatedAt" }, "idx_chat_messages_created_at");

                    b.HasIndex(new[] { "SessionId" }, "idx_chat_messages_session_id");

                    b.ToTable("chat_messages", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.ChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("chat_sessions_pkey");

                    b.HasIndex(new[] { "CreatedAt" }, "idx_chat_sessions_created_at");

                    b.HasIndex(new[] { "UserId" }, "idx_chat_sessions_user_id");

                    b.ToTable("chat_sessions", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.ChatSessionDocument", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.HasKey("SessionId", "DocumentId")
                        .HasName("chat_session_documents_pkey");

                    b.HasIndex("DocumentId");

                    b.ToTable("chat_session_documents", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid?>("AcademicTermId")
                        .HasColumnType("uuid")
                        .HasColumnName("academic_term_id");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("DocumentSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_source_id");

                    b.Property<Guid?>("DocumentTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_type_id");

                    b.Property<int>("DownloadCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("download_count");

                    b.Property<Guid?>("LanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_id");

                    b.Property<string>("Md5Hash")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("md5_hash");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<int?>("PageCount")
                        .HasColumnType("integer")
                        .HasColumnName("page_count");

                    b.Property<string>("SearchText")
                        .HasColumnType("text")
                        .HasColumnName("search_text");

                    b.Property<string>("Slug")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'pending'::character varying");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<int>("TotalChapters")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_chapters");

                    b.Property<int>("TotalChunks")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_chunks");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("view_count");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("visibility")
                        .HasDefaultValueSql("'school_wide'::character varying");

                    b.HasKey("Id")
                        .HasName("documents_pkey");

                    b.HasIndex("AcademicTermId");

                    b.HasIndex("DocumentSourceId");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("LanguageId");

                    b.HasIndex(new[] { "Md5Hash" }, "idx_documents_md5_hash");

                    b.HasIndex(new[] { "OwnerUserId" }, "idx_documents_owner_user_id");

                    b.HasIndex(new[] { "Status" }, "idx_documents_status");

                    b.HasIndex(new[] { "SubjectId" }, "idx_documents_subject_id");

                    b.HasIndex(new[] { "Visibility" }, "idx_documents_visibility");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.DocumentChapter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int>("ChapterOrder")
                        .HasColumnType("integer")
                        .HasColumnName("chapter_order");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasColumnType("numeric")
                        .HasColumnName("confidence_score");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<int?>("EndChunkIndex")
                        .HasColumnType("integer")
                        .HasColumnName("end_chunk_index");

                    b.Property<int?>("EndPage")
                        .HasColumnType("integer")
                        .HasColumnName("end_page");

                    b.Property<bool>("IsAiGenerated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ai_generated");

                    b.Property<Guid?>("ParentChapterId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_chapter_id");

                    b.Property<int?>("StartChunkIndex")
                        .HasColumnType("integer")
                        .HasColumnName("start_chunk_index");

                    b.Property<int?>("StartPage")
                        .HasColumnType("integer")
                        .HasColumnName("start_page");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("document_chapters_pkey");

                    b.HasIndex(new[] { "DocumentId" }, "idx_document_chapters_document_id");

                    b.HasIndex(new[] { "DocumentId", "ChapterOrder" }, "idx_document_chapters_order")
                        .IsUnique();

                    b.HasIndex(new[] { "ParentChapterId" }, "idx_document_chapters_parent_id");

                    b.ToTable("document_chapters", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.DocumentChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid?>("ChapterId")
                        .HasColumnType("uuid")
                        .HasColumnName("chapter_id");

                    b.Property<string>("ChunkHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("chunk_hash");

                    b.Property<int>("ChunkOrder")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_order");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<int?>("ContentTokens")
                        .HasColumnType("integer")
                        .HasColumnName("content_tokens");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(3072)")
                        .HasColumnName("embedding");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<int?>("PageNumber")
                        .HasColumnType("integer")
                        .HasColumnName("page_number");

                    b.HasKey("Id")
                        .HasName("document_chunks_pkey");

                    b.HasIndex(new[] { "ChapterId" }, "idx_document_chunks_chapter_id");

                    b.HasIndex(new[] { "DocumentId" }, "idx_document_chunks_document_id");

                    b.HasIndex(new[] { "Metadata" }, "idx_document_chunks_metadata_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "Metadata" }, "idx_document_chunks_metadata_gin"), "gin");

                    b.HasIndex(new[] { "PageNumber" }, "idx_document_chunks_page_number");

                    b.ToTable("document_chunks", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.DocumentFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("ChecksumSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("checksum_sha256");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("ExtractedText")
                        .HasColumnType("text")
                        .HasColumnName("extracted_text");

                    b.Property<string>("ExtractionStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("extraction_status")
                        .HasDefaultValueSql("'pending'::character varying");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("FileUrl")
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<string>("MimeType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mime_type");

                    b.Property<string>("OriginalFilename")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_filename");

                    b.Property<int?>("PageCount")
                        .HasColumnType("integer")
                        .HasColumnName("page_count");

                    b.Property<string>("S3Bucket")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("s3_bucket");

                    b.Property<string>("S3Key")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("s3_key");

                    b.Property<string>("StoragePath")
                        .HasColumnType("text")
                        .HasColumnName("storage_path");

                    b.HasKey("Id")
                        .HasName("document_files_pkey");

                    b.HasIndex(new[] { "DocumentId" }, "idx_document_files_document_id");

                    b.ToTable("document_files", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.DocumentReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("reason");

                    b.Property<Guid>("ReporterUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reporter_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'pending'::character varying");

                    b.HasKey("Id")
                        .HasName("document_reports_pkey");

                    b.HasIndex("DocumentId");

                    b.HasIndex("ReporterUserId");

                    b.ToTable("document_reports", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.DocumentSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("document_sources_pkey");

                    b.HasIndex(new[] { "Name" }, "document_sources_name_key")
                        .IsUnique();

                    b.ToTable("document_sources", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.DocumentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("document_types_pkey");

                    b.HasIndex(new[] { "Name" }, "document_types_name_key")
                        .IsUnique();

                    b.ToTable("document_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-111111111111"),
                            CreatedAt = new DateTime(2026, 6, 24, 23, 18, 28, 425, DateTimeKind.Utc).AddTicks(6588),
                            Name = "Giáo trình"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-222222222222"),
                            CreatedAt = new DateTime(2026, 6, 24, 23, 18, 28, 425, DateTimeKind.Utc).AddTicks(6591),
                            Name = "Slide bài giảng"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-333333333333"),
                            CreatedAt = new DateTime(2026, 6, 24, 23, 18, 28, 425, DateTimeKind.Utc).AddTicks(6593),
                            Name = "Đề thi mẫu"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-444444444444"),
                            CreatedAt = new DateTime(2026, 6, 24, 23, 18, 28, 425, DateTimeKind.Utc).AddTicks(6594),
                            Name = "Tài liệu tham khảo"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-555555555555"),
                            CreatedAt = new DateTime(2026, 6, 24, 23, 18, 28, 425, DateTimeKind.Utc).AddTicks(6596),
                            Name = "Hướng dẫn thực hành"
                        });
                });

            modelBuilder.Entity("DAL.Entities.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("languages_pkey");

                    b.HasIndex(new[] { "Code" }, "languages_code_key")
                        .IsUnique();

                    b.ToTable("languages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-111111111111"),
                            Code = "vi",
                            CreatedAt = new DateTime(2026, 6, 24, 23, 18, 28, 425, DateTimeKind.Utc).AddTicks(6662),
                            Name = "Tiếng Việt"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-222222222222"),
                            Code = "en",
                            CreatedAt = new DateTime(2026, 6, 24, 23, 18, 28, 425, DateTimeKind.Utc).AddTicks(6665),
                            Name = "Tiếng Anh"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-333333333333"),
                            Code = "ja",
                            CreatedAt = new DateTime(2026, 6, 24, 23, 18, 28, 425, DateTimeKind.Utc).AddTicks(6667),
                            Name = "Tiếng Nhật"
                        });
                });

            modelBuilder.Entity("DAL.Entities.Role", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("roles_pkey");

                    b.HasIndex(new[] { "Name" }, "roles_role_name_key")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = (short)2,
                            Name = "Lecturer"
                        },
                        new
                        {
                            Id = (short)3,
                            Name = "Student"
                        });
                });

            modelBuilder.Entity("DAL.Entities.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid?>("AcademicTermId")
                        .HasColumnType("uuid")
                        .HasColumnName("academic_term_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("subjects_pkey");

                    b.HasIndex("AcademicTermId");

                    b.HasIndex(new[] { "Code" }, "subjects_code_key")
                        .IsUnique();

                    b.ToTable("subjects", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Code = "PRN222",
                            CreatedAt = new DateTime(2026, 6, 24, 23, 18, 28, 425, DateTimeKind.Utc).AddTicks(3117),
                            Name = "Phát triển ứng dụng với .NET"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Code = "SWD392",
                            CreatedAt = new DateTime(2026, 6, 24, 23, 18, 28, 425, DateTimeKind.Utc).AddTicks(3122),
                            Name = "Kỹ nghệ phần mềm"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Code = "DBI202",
                            CreatedAt = new DateTime(2026, 6, 24, 23, 18, 28, 425, DateTimeKind.Utc).AddTicks(3123),
                            Name = "Cơ sở dữ liệu"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Code = "PRN231",
                            CreatedAt = new DateTime(2026, 6, 24, 23, 18, 28, 425, DateTimeKind.Utc).AddTicks(3125),
                            Name = "Lập trình ứng dụng phân tán"
                        });
                });

            modelBuilder.Entity("DAL.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("tags_pkey");

                    b.HasIndex(new[] { "Name" }, "tags_name_key")
                        .IsUnique();

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.UploadJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<bool>("IsNotified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_notified");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<int>("ProgressPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("progress_percent");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'pending'::character varying");

                    b.Property<string>("StoragePath")
                        .HasColumnType("text")
                        .HasColumnName("storage_path");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("upload_jobs_pkey");

                    b.HasIndex(new[] { "DocumentId" }, "idx_upload_jobs_document_id");

                    b.HasIndex(new[] { "OwnerUserId" }, "idx_upload_jobs_owner_user_id");

                    b.HasIndex(new[] { "Status" }, "idx_upload_jobs_status");

                    b.ToTable("upload_jobs", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayUsername")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("displayUsername");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("email_verified");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsBlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_blocked");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PasswordChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<short>("RoleId")
                        .HasColumnType("smallint")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Username")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "RoleId" }, "idx_users_role_id");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.UserBookmark", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId", "DocumentId")
                        .HasName("user_bookmarks_pkey");

                    b.HasIndex("DocumentId");

                    b.ToTable("user_bookmarks", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.UserSubject", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId", "SubjectId")
                        .HasName("user_subjects_pkey");

                    b.HasIndex("SubjectId");

                    b.ToTable("user_subjects", (string)null);
                });

            modelBuilder.Entity("DocumentTag", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.HasKey("DocumentId", "TagId")
                        .HasName("document_tags_pkey");

                    b.HasIndex(new[] { "TagId" }, "idx_document_tags_tag_id");

                    b.ToTable("document_tags", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.AuditLog", b =>
                {
                    b.HasOne("DAL.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("audit_logs_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Entities.ChatMessage", b =>
                {
                    b.HasOne("DAL.Entities.ChatSession", "Session")
                        .WithMany("ChatMessages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("chat_messages_session_id_fkey");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("DAL.Entities.ChatSession", b =>
                {
                    b.HasOne("DAL.Entities.User", "User")
                        .WithMany("ChatSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("chat_sessions_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Entities.ChatSessionDocument", b =>
                {
                    b.HasOne("DAL.Entities.Document", "Document")
                        .WithMany("ChatSessionDocuments")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("chat_session_documents_document_id_fkey");

                    b.HasOne("DAL.Entities.ChatSession", "Session")
                        .WithMany("SessionDocuments")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("chat_session_documents_session_id_fkey");

                    b.Navigation("Document");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("DAL.Entities.Document", b =>
                {
                    b.HasOne("DAL.Entities.AcademicTerm", "AcademicTerm")
                        .WithMany("Documents")
                        .HasForeignKey("AcademicTermId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_documents_academic_term");

                    b.HasOne("DAL.Entities.DocumentSource", "DocumentSource")
                        .WithMany("Documents")
                        .HasForeignKey("DocumentSourceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_documents_document_source");

                    b.HasOne("DAL.Entities.DocumentType", "DocumentType")
                        .WithMany("Documents")
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_documents_document_type");

                    b.HasOne("DAL.Entities.Language", "Language")
                        .WithMany("Documents")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_documents_language");

                    b.HasOne("DAL.Entities.User", "OwnerUser")
                        .WithMany("Documents")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("documents_owner_user_id_fkey");

                    b.HasOne("DAL.Entities.Subject", "Subject")
                        .WithMany("Documents")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("documents_subject_id_fkey");

                    b.Navigation("AcademicTerm");

                    b.Navigation("DocumentSource");

                    b.Navigation("DocumentType");

                    b.Navigation("Language");

                    b.Navigation("OwnerUser");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("DAL.Entities.DocumentChapter", b =>
                {
                    b.HasOne("DAL.Entities.Document", "Document")
                        .WithMany("DocumentChapters")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("document_chapters_document_id_fkey");

                    b.HasOne("DAL.Entities.DocumentChapter", "ParentChapter")
                        .WithMany("InverseParentChapter")
                        .HasForeignKey("ParentChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("document_chapters_parent_chapter_id_fkey");

                    b.Navigation("Document");

                    b.Navigation("ParentChapter");
                });

            modelBuilder.Entity("DAL.Entities.DocumentChunk", b =>
                {
                    b.HasOne("DAL.Entities.DocumentChapter", "Chapter")
                        .WithMany("DocumentChunks")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("document_chunks_chapter_id_fkey");

                    b.HasOne("DAL.Entities.Document", "Document")
                        .WithMany("DocumentChunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("document_chunks_document_id_fkey");

                    b.Navigation("Chapter");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("DAL.Entities.DocumentFile", b =>
                {
                    b.HasOne("DAL.Entities.Document", "Document")
                        .WithMany("DocumentFiles")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("document_files_document_id_fkey");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("DAL.Entities.DocumentReport", b =>
                {
                    b.HasOne("DAL.Entities.Document", "Document")
                        .WithMany("DocumentReports")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("document_reports_document_id_fkey");

                    b.HasOne("DAL.Entities.User", "ReporterUser")
                        .WithMany("DocumentReports")
                        .HasForeignKey("ReporterUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("document_reports_reporter_user_id_fkey");

                    b.Navigation("Document");

                    b.Navigation("ReporterUser");
                });

            modelBuilder.Entity("DAL.Entities.Subject", b =>
                {
                    b.HasOne("DAL.Entities.AcademicTerm", "AcademicTerm")
                        .WithMany("Subjects")
                        .HasForeignKey("AcademicTermId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_subjects_academic_term");

                    b.Navigation("AcademicTerm");
                });

            modelBuilder.Entity("DAL.Entities.UploadJob", b =>
                {
                    b.HasOne("DAL.Entities.Document", "Document")
                        .WithMany("UploadJobs")
                        .HasForeignKey("DocumentId")
                        .HasConstraintName("upload_jobs_document_id_fkey");

                    b.HasOne("DAL.Entities.User", "OwnerUser")
                        .WithMany("UploadJobs")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("upload_jobs_owner_user_id_fkey");

                    b.Navigation("Document");

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("DAL.Entities.User", b =>
                {
                    b.HasOne("DAL.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("users_role_id_fkey");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DAL.Entities.UserBookmark", b =>
                {
                    b.HasOne("DAL.Entities.Document", "Document")
                        .WithMany("UserBookmarks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_bookmarks_document_id_fkey");

                    b.HasOne("DAL.Entities.User", "User")
                        .WithMany("UserBookmarks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_bookmarks_user_id_fkey");

                    b.Navigation("Document");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Entities.UserSubject", b =>
                {
                    b.HasOne("DAL.Entities.Subject", "Subject")
                        .WithMany("UserSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_subjects_subject_id_fkey");

                    b.HasOne("DAL.Entities.User", "User")
                        .WithMany("UserSubjects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_subjects_user_id_fkey");

                    b.Navigation("Subject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DocumentTag", b =>
                {
                    b.HasOne("DAL.Entities.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("document_tags_document_id_fkey");

                    b.HasOne("DAL.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("document_tags_tag_id_fkey");
                });

            modelBuilder.Entity("DAL.Entities.AcademicTerm", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("DAL.Entities.ChatSession", b =>
                {
                    b.Navigation("ChatMessages");

                    b.Navigation("SessionDocuments");
                });

            modelBuilder.Entity("DAL.Entities.Document", b =>
                {
                    b.Navigation("ChatSessionDocuments");

                    b.Navigation("DocumentChapters");

                    b.Navigation("DocumentChunks");

                    b.Navigation("DocumentFiles");

                    b.Navigation("DocumentReports");

                    b.Navigation("UploadJobs");

                    b.Navigation("UserBookmarks");
                });

            modelBuilder.Entity("DAL.Entities.DocumentChapter", b =>
                {
                    b.Navigation("DocumentChunks");

                    b.Navigation("InverseParentChapter");
                });

            modelBuilder.Entity("DAL.Entities.DocumentSource", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("DAL.Entities.DocumentType", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("DAL.Entities.Language", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("DAL.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("DAL.Entities.Subject", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("UserSubjects");
                });

            modelBuilder.Entity("DAL.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("ChatSessions");

                    b.Navigation("DocumentReports");

                    b.Navigation("Documents");

                    b.Navigation("UploadJobs");

                    b.Navigation("UserBookmarks");

                    b.Navigation("UserSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
